included:
  - Sources
  - Tests

opt_in_rules:
  - explicit_acl
  - explicit_top_level_acl

excluded:
  - .build/
  - .swiftpm/

# Configure built-in access control rules
explicit_acl:
  severity: warning

explicit_top_level_acl:
  severity: warning
