# AsyncNet CI/CD Pipeline

name: AsyncNet CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest, macos-13, macos-14]
        target: [macos, ios, tvos]
        swift-version: [6.0]
        build: [spm, xcode]
        # Exclude incompatible combinations
        exclude:
          - target: ios
            build: spm
          - target: tvos
            build: spm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift (macOS)
        if: runner.os == 'macOS' && matrix.target == 'macos'
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Set up Xcode 16 (macOS only)
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Build (macOS SPM)
        if: matrix.target == 'macos' && matrix.build == 'spm'
        run: swift build -Xswiftc -strict-concurrency=complete

      - name: Build (macOS Xcode)
        if: matrix.target == 'macos' && matrix.build == 'xcode'
        run: xcodebuild -scheme AsyncNet -destination "platform=macOS" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build

      - name: Build (iOS)
        if: matrix.target == 'ios'
        run: xcodebuild -scheme AsyncNet -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build

      - name: Build (tvOS)
        if: matrix.target == 'tvos'
        run: xcodebuild -scheme AsyncNet -destination "platform=tvOS Simulator,name=Apple TV,OS=latest" -sdk appletvsimulator CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build

      - name: Run tests
        run: |
          if [[ "${{ matrix.target }}" == "macos" ]]; then
            if [[ "${{ matrix.build }}" == "spm" ]]; then
              swift test --enable-code-coverage
            else
              xcodebuild test -scheme AsyncNet -destination "platform=macOS" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
            fi
          elif [[ "${{ matrix.target }}" == "ios" ]]; then
            xcodebuild test -scheme AsyncNet -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          elif [[ "${{ matrix.target }}" == "tvos" ]]; then
            xcodebuild test -scheme AsyncNet -destination "platform=tvOS Simulator,name=Apple TV,OS=latest" -sdk appletvsimulator CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          else
            echo "Unknown target: ${{ matrix.target }}"
            exit 1
          fi

      - name: Check coverage profdata
        if: matrix.target == 'macos' && matrix.build == 'spm'
        id: coverage_profdata_check
        run: |
          if ls .build/debug/codecov/*.profdata 1> /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload coverage profdata
        if: matrix.target == 'macos' && matrix.build == 'spm' && steps.coverage_profdata_check.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-profdata
          path: .build/debug/codecov/*.profdata

# Note: iPadOS builds are not included in the current matrix for simplicity
# To add iPadOS support, add 'ipados' to the target axis and update the test script accordingly
