# AsyncNet CI/CD Pipeline

name: AsyncNet CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [macOS-15, macOS-16, iOS-18, iPadOS-18]
        swift-version: [6.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: |
          if [[ "${{ matrix.platform }}" == macOS* ]]; then
            swift build -Xswiftc -strict-concurrency=complete
          else
            xcodebuild -scheme AsyncNet -destination "platform=${{ matrix.platform }},OS=latest,name=iPhone 14" build
          fi

      - name: Run tests
        run: |
          if [[ "${{ matrix.platform }}" == macOS* ]]; then
            swift test --enable-code-coverage
          else
            xcodebuild test -scheme AsyncNet -destination "platform=${{ matrix.platform }},OS=latest,name=iPhone 14"
          fi

      - name: Upload coverage
        if: matrix.platform == 'macOS-16'
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .build/debug/codecov/
